name: Dependency Review

on:
  workflow_call:
  # To test on this repo
  pull_request: 

permissions:
  contents: read

jobs:
  # We have to update the dependency graph for the current branch manually
  # if the repo contains unsupported languages.
  submit-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Detect languages
        id: detect
        run: |
          REPO_LANGUAGES=$(gh api repos/${{ github.repository }}/languages | jq -r 'keys[]')
          
          echo "has_scala=$(echo "$REPO_LANGUAGES" | grep -qx 'Scala' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "has_kotlin=$(echo "$REPO_LANGUAGES" | grep -qx 'Kotlin' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Set up SBT
        if: ${{ steps.detect.outputs.has_scala == 'true' }}
        uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0

      - name: Submit Scala dependencies 
        if: ${{ steps.detect.outputs.has_scala == 'true' }}
        uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3

      - name: Submit Kotlin dependencies
        if: ${{ steps.detect.outputs.has_kotlin == 'true' }}
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    needs: submit-dependencies
    steps:
      - uses: actions/checkout@v7

      - uses: actions/dependency-review-action@v5
        with:
          comment-summary-in-pr: always
