name: Dependency Review

on:
  workflow_call:

permissions:
  contents: read

jobs:
  # We have to update the dependency graph for the current branch manually
  # if the repo contains unsupported languages.
  submit-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Check for unsupported languages
        id: check-lang
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LANGUAGES=$(gh api repos/${{ github.repository }}/languages)
          if echo "$LANGUAGES" | jq -e 'has("Scala")' > /dev/null; then
            echo "has_scala=true" >> $GITHUB_OUTPUT
          else
            echo "has_scala=false" >> $GITHUB_OUTPUT
          fi

      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
        if: ${{ steps.check-lang.outputs.has_scala == 'true' }}

      - uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
        if: ${{ steps.check-lang.outputs.has_scala == 'true' }}

  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    needs: submit-dependencies
    steps:
      - uses: actions/checkout@v7

      - uses: actions/dependency-review-action@v5
        with:
          # TODO is this helpful?
          show-patched-versions: true
          comment-summary-in-pr: always
          
